import MainHeader from "@/components/main-header";
import "./globals.css";

export const metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
